workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build ios --simulator
    artifacts:
      - build/ios/Runner.app # Path to the generated .app file
